In [28]:
import pandas as pd
df = pd.read_csv("ce.series.txt", sep="\t")  # tab-separated

In [29]:
# datatype said series id ended with 01 --> ALL EMPLOYEES, THOUSANDS
# that's what we what

In [30]:
df.columns

Index(['series_id        ', 'supersector_code', 'industry_code',
       'data_type_code', 'seasonal', 'series_title', 'footnote_codes',
       'begin_year', 'begin_period', 'end_year', 'end_period'],
      dtype='str')

In [31]:
df.columns = [col.strip() for col in df.columns]
df['series_id'] = df['series_id'].str.strip()
df_all_employees = df[(df['data_type_code']=="01") &  (df['seasonal']=="S")]
# labels-> label 0, 1 ,2 
# df should look like this
'''
Series ID           Layer 1              Layer 2                                        Layer 3                     Layer 4           Layer 5 
CES1021211501       Mining and logging   Mining, quarrying, and oil and gas extraction  Mining (except oil and gas) Coal mining       underground coal mining


'''

'\nSeries ID           Layer 1              Layer 2                                        Layer 3                     Layer 4           Layer 5 \nCES1021211501       Mining and logging   Mining, quarrying, and oil and gas extraction  Mining (except oil and gas) Coal mining       underground coal mining\n\n\n'

In [32]:
df_all_employees.head(5)

,series_id,supersector_code,industry_code,data_type_code,seasonal,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
0,CES0000000001,0,0,01,S,"All employees, thousands, total nonfarm, seaso...",NaN,1939,M01,2026,M05
4,CES0500000001,5,5000000,01,S,"All employees, thousands, total private, seaso...",NaN,1939,M01,2026,M05
32,CES0600000001,6,6000000,01,S,"All employees, thousands, goods-producing, sea...",NaN,1939,M01,2026,M05
54,CES0700000001,7,7000000,01,S,"All employees, thousands, service-providing, s...",NaN,1939,M01,2026,M05
57,CES0800000001,8,8000000,01,S,"All employees, thousands, private service-prov...",NaN,1939,M01,2026,M05

In [33]:
df_industry_code =pd.read_csv("ce.industry.txt", sep="\t")

In [40]:
df_industry_code

,industry_code,naics_code,publishing_status,industry_name,display_level,selectable,sort_sequence
0,0,-,B,Total nonfarm,0,T,1
1,5000000,-,A,Total private,1,T,2
2,6000000,-,A,Goods-producing,1,T,3
3,7000000,-,B,Service-providing,1,T,4
4,8000000,-,A,Private service-providing,1,T,5
...,...,...,...,...,...,...,...
845,90932221,-,B,Local government utilities,5,T,846
846,90932480,-,B,Local government transportation,5,T,847
847,90932622,-,B,Local hospitals,5,T,848
848,90932920,-,B,Local government general administration,5,T,849
849,90932999,-,B,Other local government,5,T,850

In [41]:
df_all_employees.head(5)

,series_id,supersector_code,industry_code,data_type_code,seasonal,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
0,CES0000000001,0,0,01,S,"All employees, thousands, total nonfarm, seaso...",NaN,1939,M01,2026,M05
4,CES0500000001,5,5000000,01,S,"All employees, thousands, total private, seaso...",NaN,1939,M01,2026,M05
32,CES0600000001,6,6000000,01,S,"All employees, thousands, goods-producing, sea...",NaN,1939,M01,2026,M05
54,CES0700000001,7,7000000,01,S,"All employees, thousands, service-providing, s...",NaN,1939,M01,2026,M05
57,CES0800000001,8,8000000,01,S,"All employees, thousands, private service-prov...",NaN,1939,M01,2026,M05

In [ ]:
pd.merge()

In [43]:
df_ae_merged = pd.merge(df_all_employees, df_industry_code[['industry_code','industry_name']], on='industry_code', how='left')

In [48]:
#dddf_ae_merged.tail(20)

In [11]:
'''
double for loops; 
second for loop's item B check the first loop one (item A);
first loop for i in range(i+1, len )
second loop  for j in range(0, i+1,  -1)


if less than 4 match -> break

find at least 4 match and if item B and item A's rightest unmatched is a 0, 
item A is item B's parent; record in a dictionary { parent: [child]}


check until reaching 0 (if it's actually the same item, itself is a parent; we can skip.. and it won't exist in our map) 
'''

"\ndouble for loops; \nsecond for loop's item B check the first loop one (item A);\nfirst loop for i in range(i+1, len )\nsecond loop  for j in range(0, i+1,  -1)\n\n\nif less than 4 match -> break\n\nfind at least 4 match and if item B and item A's rightest unmatched is a 0, \nitem A is item B's parent; record in a dictionary { parent: [child]}\n\n\ncheck until reaching 0 (if it's actually the same item, itself is a parent; we can skip.. and it won't exist in our map) \n"

In [49]:
value_pairs = df_ae_merged[['series_id','industry_name']].values.tolist()

In [50]:
for i in range( 0,-1,-1):
    print(i)

0

In [51]:
def first_mismatch(s1, s2):
    for i, (c1, c2) in enumerate(zip(s1, s2)):
        if c1 != c2:
            return i
    return min(len(s1), len(s2))  # one is a prefix of the other

In [52]:
value_pairs[0][1],value_pairs[0][0]

('Total nonfarm', 'CES0000000001')

In [53]:
len(value_pairs)

842

In [54]:
hierachy_maps  = {}
for i in range(1, len(value_pairs)):
    for j in range( i-1, -1, -1):
        new_id, child_categroy = value_pairs[i][0],value_pairs[i][1]
        old_id, parent_category = value_pairs[j][0], value_pairs[j][1]
        pos = first_mismatch(old_id, new_id)
        # import pdb
        # pdb.set_trace()
        if pos > 3 and old_id[pos] == '0':
            hierachy_maps[child_categroy]=parent_category
            break

In [101]:
first_mismatch("CES5051929001", "CES5500000001")

4

In [18]:
#hierachy_maps.items()

In [55]:
[(k,v) for k,v in hierachy_maps.items() if "$" in k or "$" in v ]

[]

In [20]:
'''
next step is do dfs; build the sequences;  

for each key, keep resolving till reaching the parent, and record them in a []

'''

'\nnext step is do dfs; build the sequences;  \n\nfor each key, keep resolving till reaching the parent, and record them in a []\n\n'

In [100]:
hierachy_maps['Financial activities']

'Web search portals and all other information services'

In [62]:
label_paths = {}

In [74]:
for child_key,v in hierachy_maps.items():
    parent_category = v
    path = child_key
    while True: 
        path = parent_category + "&" + path 
        if parent_category in hierachy_maps:
            parent_category = hierachy_maps[parent_category]
        else: 
            break
    # while parent_category in hierachy_maps:
    #     path = parent_category + "&" + path 
    #     parent_category = hierachy_maps[parent_category]
    
    label_paths[child_key] = path

In [75]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [98]:
label_paths['Financial activities']

'Information&Web search portals, libraries, archives, and other information services&Web search portals and all other information services&Financial activities'

In [78]:
df_cat_names = pd.DataFrame(data=[label_paths]).T

In [79]:
df_cat_names.columns = ["Stacked Category"]

In [80]:
df_cat_names= df_cat_names.reset_index()

In [87]:
df_cat_names = df_cat_names.rename(columns={"index": "industry_name"})

In [88]:
df_cat_names.head(15)

,industry_name,Stacked Category
0,Total private,Total nonfarm&Total private
1,Goods-producing,Total nonfarm&Goods-producing
2,Service-providing,Total nonfarm&Service-providing
3,Private service-providing,Total nonfarm&Private service-providing
4,Logging,Mining and logging&Logging
5,"Mining, quarrying, and oil and gas extraction","Mining and logging&Mining, quarrying, and oil ..."
6,Oil and gas extraction,"Mining and logging&Mining, quarrying, and oil ..."
7,Mining (except oil and gas),"Mining and logging&Mining, quarrying, and oil ..."
8,Coal mining,"Mining and logging&Mining, quarrying, and oil ..."
9,Surface coal mining,"Mining and logging&Mining, quarrying, and oil ..."
10,Underground coal mining,"Mining and logging&Mining, quarrying, and oil ..."
11,Metal ore mining,"Mining and logging&Mining, quarrying, and oil ..."
12,Gold ore and silver ore mining,"Mining and logging&Mining, quarrying, and oil ..."
13,"Iron ore, copper, nickel, lead, zinc, and othe...","Mining and logging&Mining, quarrying, and oil ..."
14,Nonmetallic mineral mining and quarrying,"Mining and logging&Mining, quarrying, and oil ..."

In [89]:
df_ae_merged.columns

Index(['series_id', 'supersector_code', 'industry_code', 'data_type_code',
       'seasonal', 'series_title', 'footnote_codes', 'begin_year',
       'begin_period', 'end_year', 'end_period', 'industry_name'],
      dtype='str')

In [92]:
df_merge = pd.merge(df_ae_merged, df_cat_names,left_on='industry_name', right_on='industry_name',how='left')

In [94]:

df_merge

,series_id,supersector_code,industry_code,data_type_code,seasonal,series_title,footnote_codes,begin_year,begin_period,end_year,end_period,industry_name,Stacked Category
0,CES0000000001,0,0,01,S,"All employees, thousands, total nonfarm, seaso...",NaN,1939,M01,2026,M05,Total nonfarm,NaN
1,CES0500000001,5,5000000,01,S,"All employees, thousands, total private, seaso...",NaN,1939,M01,2026,M05,Total private,Total nonfarm&Total private
2,CES0600000001,6,6000000,01,S,"All employees, thousands, goods-producing, sea...",NaN,1939,M01,2026,M05,Goods-producing,Total nonfarm&Goods-producing
3,CES0700000001,7,7000000,01,S,"All employees, thousands, service-providing, s...",NaN,1939,M01,2026,M05,Service-providing,Total nonfarm&Service-providing
4,CES0800000001,8,8000000,01,S,"All employees, thousands, private service-prov...",NaN,1939,M01,2026,M05,Private service-providing,Total nonfarm&Private service-providing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,CES9093222101,90,90932221,01,S,"All employees, thousands, local government uti...",I,1990,M01,2026,M04,Local government utilities,"Government&Local government&Local government, ..."
838,CES9093248001,90,90932480,01,S,"All employees, thousands, local government tra...",I,1990,M01,2026,M04,Local government transportation,"Government&Local government&Local government, ..."
839,CES9093262201,90,90932622,01,S,"All employees, thousands, local hospitals, sea...",I,1972,M01,2026,M04,Local hospitals,"Government&Local government&Local government, ..."
840,CES9093292001,90,90932920,01,S,"All employees, thousands, local government gen...",I,1990,M01,2026,M04,Local government general administration,"Government&Local government&Local government, ..."
841,CES9093299901,90,90932999,01,S,"All employees, thousands, other local governme...",I,1990,M01,2026,M04,Other local government,"Government&Local government&Local government, ..."

In [95]:
df_result = pd.concat([df_merge, df_merge['Stacked Category'].str.split("&",expand=True)], axis=1)

In [97]:
df_result.to_excel("result.xlsx")